services:
  database:
    image: postgres:15
    container_name: fleet_management_db
    environment:
      POSTGRES_DB: fleet_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      DB_HOST: localhost
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: